---
title: "Simulation1 Output"
output: html_document
---


\
\
\
\
\

```{r, message=FALSE, warning=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
library(dplyr)
load("simulation1_data/res_ratio_t2.rda")
load("simulation1_data/res_coef_t2.rda")
```


```{r results='asis', echo=FALSE, message=FALSE, warning=FALSE}
res_ratio_t2 %>% 
  kbl(caption = "ratio of Z_cont coefficient to Z_bi coefficient") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  pack_rows("None standardization", 1, 1, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("1 SD standardization", 2, 2, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("Andrew Gelman", 3, 3, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("Min-max", 4, 4, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("New standardization, no 2sd", 5, 5, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("New standardization, with 2sd", 6, 6, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("New standardization, no 2sd", 7, 7, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("New standardization, with 2sd", 8, 8, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("New standardization, no 2sd", 9, 9, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("New standardization, with 2sd", 10, 10, label_row_css = "background-color: white; color: blue;") 
```

\
\
\
\
\
```{r results='asis', echo=FALSE, message=FALSE, warning=FALSE}
res_coef_t2 %>% 
  kbl(caption = "standardized coefficients") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  pack_rows("None standardization", 1, 5, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("1 SD standardization", 6, 10, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("Andrew Gelman", 11, 15, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("Min-max", 16, 20, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("New standardization, no 2sd", 21, 24, label_row_css = "background-color: white; color: blue;") %>%
  pack_rows("New standardization, with 2sd", 25, 28, label_row_css = "background-color: white; color: blue;")
```

\
\
\
\
\